// flow-typed signature: 9e5e90f89ef41732c42b43d77d3d41fc
// flow-typed version: <<STUB>>/deline_v^1.0.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deline/build/deline' {
  declare module.exports: any;
}

declare module 'deline/deline' {
  declare module.exports: any;
}

declare module 'deline/test/deline-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deline/build/deline.js' {
  declare module.exports: $Exports<'deline/build/deline'>;
}
declare module 'deline/deline.js' {
  declare module.exports: $Exports<'deline/deline'>;
}
declare module 'deline/test/deline-tests.js' {
  declare module.exports: $Exports<'deline/test/deline-tests'>;
}
